version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  duplication:
    enabled: true
    exclude_patterns:
      - "spec/"
    config:
      languages:
        ruby:
          mass_threshold: 30
exclude_patterns:
- config/
- db/
- vendor/
