version: '2'
services:
  xanyah-db:
    image: postgres:9.6
    container_name: xanyah-db
    environment:
      POSTGRES_DB: xanyah_development
      POSTGRES_USER: xanyah
      POSTGRES_PASSWORD:
    ports:
      - 6501:5432/tcp
  xanyah-db-test:
    image: postgres:9.6
    container_name: xanyah-db-test
    environment:
      POSTGRES_DB: xanyah_test
      POSTGRES_USER: xanyah
      POSTGRES_PASSWORD:
    ports:
      - 6502:5432/tcp
